# https://taskfile.dev

version: "3"

dotenv:
  - ".env"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - if [ "$DEV_PLATFORM" = "linux" ]; then docker start homedb-dev; fi
      - air
    silent: true

  build:
    cmds:
      - if [ "$DEV_PLATFORM" = "linux" ]; then docker start homedb-dev; fi
      - sqlc generate
      - templ generate
      - npx @tailwindcss/cli -i ./static/css/styles.css -o ./static/css/out.css
      - go build -o ./tmp/main ./cmd/homedb
    silent: true

  clean:
    cmds:
      - rm -rf ./tmp
