// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, amount, unit, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, amount, unit, user_id
`

type CreateItemParams struct {
	Name   string
	Amount int32
	Unit   ItemUnit
	UserID uuid.UUID
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.UserID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.UserID,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :one
DELETE FROM items
WHERE id = $1
RETURNING id, name, amount, unit, user_id
`

func (q *Queries) DeleteItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, deleteItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.UserID,
	)
	return i, err
}

const filterItemsByName = `-- name: FilterItemsByName :many
SELECT id, name, amount, unit, user_id FROM items
WHERE user_id = $1
AND name ILIKE $2
ORDER BY name ASC
`

type FilterItemsByNameParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) FilterItemsByName(ctx context.Context, arg FilterItemsByNameParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, filterItemsByName, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, amount, unit, user_id FROM items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.UserID,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, amount, unit, user_id FROM items
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListItems(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
  name = $1,
  amount = $2,
  unit = $3
WHERE id = $4
RETURNING id, name, amount, unit, user_id
`

type UpdateItemParams struct {
	Name   string
	Amount int32
	Unit   ItemUnit
	ID     uuid.UUID
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.UserID,
	)
	return i, err
}
